config/routes.rb
Rails.application.routes.draw do
  root to: 'web/home#index'
  # devise_for :students
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations',
    passwords: 'students/passwords',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  # before_action  : authenticate_student! 
  # student_signed_in? 
  # current_student 
  # student_session
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/web/home_controller.rb
class Web::HomeController < WebController
    def index
    
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
    layout 'web'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title DemoDeviseGem
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/web.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title DemoDeviseGem
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/students/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",                 \
        count: resource.errors.count,                       \
        resource: resource.class.model_name.human.downcase) \
    ul
      - resource.errors.full_messages.each do |message|
        li= message

app/views/students/shared/_links.html.slim
- if controller_name != 'sessions'
  .form_link
    i.fa.fa-sign-in
    = link_to "Sign in", new_session_path(resource_name)
br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  .form_link
    i.fa.fa-pencil-square-o
    = link_to "Sign up", new_registration_path(resource_name)
  br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  .form_link
    i.fa.fa-question-circle-o
    = link_to "Forgot your password ?", new_password_path(resource_name)
  br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  .form_link
    = link_to "Didn't receive confirmation instructions ?", new_confirmation_path(resource_name)
  br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  .form_link  
    = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    .form_link
      = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    br/

app/views/web/home/index.html.slim
.page 
    .header 
        .container 
            .header_logo 
                =image_tag('logo.png',class:"logo")
            .header_menu 
                = link_to "#",class: "link_menu" do 
                    |Home
                = link_to "#",class: "link_menu" do 
                    |Home
                = link_to "#",class: "link_menu" do 
                    |Home
                = link_to "#",class: "link_menu" do 
                    |Home
                = link_to "#",class: "link_menu" do 
                    |Home
            .header_profile 
                .profile-details
                    - if current_student.present?
                        =image_tag('1.jpeg', class:"profile_pic")          
                        i.fa.fa-caret-down.profile_icon aria-hidden="true"
                            .sub_menu
                                .text_sub_menu
                                    | Signed in as nohssiw
                                = link_to edit_student_registration_path,class: "link_sub_menu" do 
                                    i.fa.fa-pencil-square-o
                                    | Edit Profile
                                = link_to "#",class: "link_sub_menu" do
                                    i.fa.fa-cogs 
                                    | Settings
                                =link_to destroy_student_session_path(),class: "link_sub_menu", method: "delete" do 
                                    i.fa.fa-sign-out
                                    | Sign Out
                        
                    - else
                        =link_to new_student_registration_path(),class: "m-r-10 btn btn-outline-danger btn-sign-up-in" do 
                            |Sign Up
                        =link_to  new_student_session_path(),class: "btn btn-outline-danger btn-sign-up-in" do 
                            |Sign In
                    